repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-toml
    - id: detect-private-key
    - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
